sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm i -g cordova@^7.1.0
  - npm run apply:dash
# after_success:
#   - npm run exec:coveralls
